### ISSUE TITLE
As a programmer create documentation for NPC's interactions : 2 Hours

### ISSUE THREAD

**Issue by Michael-Curtis** [UoSGamesGroups/first-semester-lvl4-5-group-7#23]
Create documentation to show all the coding needed to create all the interactions with the NPC's. 2 Hours

**Comment by ThomasJamesBarrett** [comment]
I've just realised that we may need four different character types at least. (Man, Woman, Boy, Girl) Is this getting accounted for by the designers of the group?

**Comment by Michael-Curtis** [comment]
Hey Tom,

each NPC in the game is unique and thus has unique preferences. Therefore seperating NPCs out by gender is likely to be redundant.
