### ISSUE TITLE
Develop NPC assets : 3 Hours

### ISSUE THREAD

**Issue by ghost** [UoSGamesGroups/first-semester-lvl4-5-group-7#36]
Design and develop assets for NPC characters in the bookstore, in addition to the ones from last week.

**Comment by AnastaziaH** [comment]
![hodgeheg nyello](https://cloud.githubusercontent.com/assets/22730241/20019604/14df226c-a2c5-11e6-9387-957584b98ad8.gif)
![dancin bun](https://cloud.githubusercontent.com/assets/22730241/20019609/1a585d9e-a2c5-11e6-9edb-ed1dc27174f0.gif)
![happy hodgeheg](https://cloud.githubusercontent.com/assets/22730241/20019613/1d7587fe-a2c5-11e6-8059-cd1bae570511.gif)
