### ISSUE TITLE
Design a new background for the game interface : 2 Hours

### ISSUE THREAD

**Issue by ghost** [UoSGamesGroups/first-semester-lvl4-5-group-7#50]
Design a new layout for the background of the game. Keep in mind gestalt principles and visual hierarchies. (See 1st year notes for reference)

**Comment by Michael-Curtis** [comment]
Designed a scene for the player to see. Will implement this new background design ASAP.

**Comment by Michael-Curtis** [comment]
Made some mock ups in Photoshop using our assets and some placeholders where needed, I have completely redesigned the scene to try and drop the dead space and apply my knowledge of Gestalt Principles and the rule of thirds. I will be discussing our design choices with the whole group at the next group meeting to ensure all members are comfortable with and understand the reason for these changes.
