### ISSUE TITLE
Implement the new background : 2 Hours

### ISSUE THREAD

**Issue by ghost** [UoSGamesGroups/first-semester-lvl4-5-group-7#51]
Draw, colour and upload sprites to GitHub for implementation. (Optional) come into labs and help Elliot place them in Unity project.

**Comment by Michael-Curtis** [comment]
Created and implemented the designs I have made. Also created a few more sprites. A new curved counter asset to better fit with the scene. A gem icon for currency and an icon to open a buying/selling screen.
