### ISSUE TITLE
Implement a new User Interface : 2 Hours

### ISSUE THREAD

**Issue by limejuice123** [UoSGamesGroups/first-semester-lvl4-5-group-7#53]
Draw and colour new GUI sprites and upload them to GitHub. (Optional) come into labs and help Elliot to place them in Unity project.

**Comment by AnastaziaH** [comment]
Designed some new books and added more genres. Incomplete. 1.5 hours.

**Comment by AnastaziaH** [comment]
Added buttons to the Overlay Assets folder. 1 hour.
